// <auto-generated />
namespace Dal.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddResumeAndAddress : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddResumeAndAddress));
        
        string IMigrationMetadata.Id
        {
            get { return "201308290019135_AddResumeAndAddress"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
